### ISSUE TITLE
Unable to derive ValueConverter

### ISSUE THREAD

**Issue by PawelJ-PL** [eikek/yamusca#237]
Hi,

I'm trying to use example from README in my code, but I an got error.

My code:

```scala
import yamusca.converter.ValueConverter
import yamusca.implicits._
import yamusca.derive._

case class Data (name: String, items: List[String])

object Data {
  implicit val dataConv: ValueConverter[Data] = deriveValueConverter[Data]
}
```

Error:

```
[info] compiling 1 Scala source to ~/IdeaProjects/project/target/scala-2.13/classes ...
[error] ~/IdeaProjects/project/src/main/scala/app/Data.scala:10:69: not found: type Value
[error]   implicit val dataConv: ValueConverter[Data] = deriveValueConverter[Data]
[error]                                                                     ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

Tried with version `0.9.0` and `0.10.0`

**Comment by eikek** [comment]
I think you need to do a `import yamusca.imports._` as well to bring required classes in scope.

**Comment by PawelJ-PL** [comment]
Thank you for explanation. I was thinking, that all snippets contains all necessary imports.

with `import yamusca.imports._` derivation works as expected.

**Comment by eikek** [comment]
> Thank you for explanation. I was thinking, that all snippets contains all necessary imports.

This is to make the snippets a bit shorter for easier reading, but it would be better to explicitly mention this.



> with `import yamusca.imports._` derivation works as expected.

👍🏼 I'll close this then
