### ISSUE TITLE
Option to check for missing Context

### ISSUE THREAD

**Issue by ngbinh** [eikek/yamusca#30]
Hi, 

I would like to make sure the provided `Context` should contain all the necessary variables of the template. For example:
`mustache.parse("{{#a}}{{b}}{{/a}}".renderResult(Context("a"->Value.of(true)))"` should fail with missing `"b"` in `Context` while it should work fine with `Context("a" -> Value.map("b" -> Value.of("b")))`

Is there a way for me do to so?

Thanks

**Comment by eikek** [comment]
Hello,
you could maybe stack a custom context, that throws exceptions.
```scala
object ThrowingContext {
  def apply(ctx: Context): Context =
    ctx :: Context.from(name => sys.error(s"Cannot find $name in context"))
}
```
This must be stacked such that the throwing-context is used whenever no other context has a value. Then you have to remember to first wrap your context.

Usage would be like this:
```scala
sbt:yamusca-core> console
[info] Starting scala interpreter...
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.
import yamusca.imports._
import yamusca.implicits._
import yamusca.parser.ParseInput

scala> val ctx = Context("a"->Value.of(true))
val ctx: yamusca.context.Context = yamusca.context$Context$$anon$2@16ec03c

scala> val tctx = yamusca.context.ThrowingContext(ctx)
val tctx: yamusca.context.Context = StackedContext(yamusca.context$Context$$anon$2@16ec03c,List(yamusca.context$Context$$anon$3@3a90f635))

scala> ctx.render(mustache"{{#a}}{{b}}{{/a}}")
val res0: String = ""

scala> tctx.render(mustache"{{#a}}{{b}}{{/a}}")
java.lang.RuntimeException: Cannot find b in context
  at scala.sys.package$.error(package.scala:27)
  at yamusca.context$ThrowingContext$.$anonfun$apply$1(context.scala:25)
  at yamusca.context$Context$$anon$3.find(context.scala:74)
  at yamusca.context$StackedContext.loop$1(context.scala:34)
  ... 40 elided

scala> tctx.render(mustache"{{#a}}123{{/a}}")
val res2: String = 123
```

**Comment by eikek** [comment]
Actually, I think something like this should be provided by the library. It should be possible to return a list of all keys that were not found during template expansion. Then people could decide to throw or just log.

**Comment by ngbinh** [comment]
Thanks for the quick reply. I would also like to flag missing sections keys also. Is it possible?

**Comment by ngbinh** [comment]
oh, nvm. I get it now. It's so cool that the solution is quite simple. And yes, ability to show all missing keys is definitely very helpful

**Comment by ngbinh** [comment]
looks like it is done. Thanks.
