### ISSUE TITLE
Support {{-first}} and {{-last}} on arrays, like in jmustache

### ISSUE THREAD

**Issue by djjorjinho** [eikek/yamusca#5]
Good afternoon,

Is it possible for your library to support {{-first}} and {{-last}} variables when iterating arrays, just like in [jmustache](https://github.com/samskivert/jmustache#-first-and--last)?

I understand this is not standard mustache, but I have a use case where I'm trying to generate json requests for my team's integration tests, the services don't allow null fields in the json, so our workaround is to have a template for every combination of json fields, or assemble the json strings outside the template. This way there's no null fields and no dangling commas.

This feature would really help us reduce complexity and keep rendering domain inside the template file.

**Comment by eikek** [comment]
Hi, thanks for your input! I think that should be possible. I'll see if I can add this when I have some time.

**Comment by djjorjinho** [comment]
Thank you for your speedy reply @eikek , this feature means a lot to our team :)

**Comment by eikek** [comment]
@djjorjinho luckily it seems that it wasn't so hard to add …. Can you maybe test the branch a bit? It would feel little better when publishing to maven central.

**Comment by djjorjinho** [comment]
Just finished playing with the branch. Looks good to go. Thank you so much for the speedy resolve!

**Comment by eikek** [comment]
You are welcome! Thanks a lot for testing! I'll push a new version soon.

Am 1. Februar 2019 22:38:27 MEZ schrieb djjorjinho <notifications@github.com>:
>Just finished playing with the branch. Looks good to go. Thank you so
>much for the speedy resolve!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/eikek/yamusca/issues/5#issuecomment-459876530

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
