### ISSUE TITLE
Error with nested objects

### ISSUE THREAD

**Issue by macalinao** [eikek/yamusca#7]
First off, thanks for making such a great library. Everyone else is using reflection-- this is the only solution I've seen based on Circe.

My problem is that my templates are not rendering as expected.

Data:

```
{
  "a": {
    "b": {
      "c": true
    }
  }
}
```

Template:

```
{{#a.b}}
{{#a.b.c}}
Hello
{{/a.b.c}}
World
{{/a.b}}
```

Expected:

```
Hello
World
```

Actual

```
World
```

Any help here is greatly appreciated. Thanks!

**Comment by eikek** [comment]
@macalinao Thanks for your kind words!

I'm not so sure, but I thought once there is an open section like `{{#a.b}}` everything inside wouldn't need the `a.b` prefix (since it is all inside that `a.b` namespace). So the template would be 

```
{{#a.b}}
{{#c}}
Hello
{{/c}}
World
{{/a.b}}
```
What do you think?

**Comment by macalinao** [comment]
That makes sense. What if I have an object like this:

```
{
  "a": {
    "b": {
      "c": true
    }
  },
  "d": {
    "e": false
  }
}
```

If I'm able to do

```
{{#a.b}}
{{#d.e}}
test
{{/d.e}}
{{/a.b}}
```

then I think this should work for my use case.

**Comment by eikek** [comment]
Ah, now I see. You mean that it should go look from the beginning when inside a section. You're right, your first example should work as you said. Sorry for the misunderstanding!

I think, your second example actually works with yamusca. I just tried it with 0.5.0. It should print nothing and if the data is changed to `"e": true`, then it should print `test`, correct?

**Comment by eikek** [comment]
Hello @macalinao, I just pushed a fix to this bug. If you find some time, maybe you could test it against more of your inputs? Thank you for reporting this!

**Comment by macalinao** [comment]
Thanks for pushing this!
